//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public company_employee()
        {
            this.calender_events = new HashSet<calender_events>();
            this.company_employee1 = new HashSet<company_employee>();
            this.course_registration = new HashSet<course_registration>();
            this.notification_seen = new HashSet<notification_seen>();
        }
    
        public int user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string user_full_name { get; set; }
        public string user_title { get; set; }
        public string user_department { get; set; }
        public Nullable<int> manager_id { get; set; }
        public Nullable<System.DateTime> date_of_joining { get; set; }
        public string is_admin { get; set; }
        public string is_manager { get; set; }
        public string is_instructor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calender_events> calender_events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<company_employee> company_employee1 { get; set; }
        public virtual company_employee company_employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_registration> course_registration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification_seen> notification_seen { get; set; }
    }
}
