//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class instructor
    {
        public int instructor_id { get; set; }
        public string instructor_name { get; set; }
        public string instructor_type { get; set; }
        public string instructor_contact { get; set; }
        public string additional_details { get; set; }
    }
}
