//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification_seen
    {
        public int seen_id { get; set; }
        public Nullable<int> not_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual company_employee company_employee { get; set; }
        public virtual notification notification { get; set; }
    }
}
